name: Build and Push to ACR Serivce Api

on:
  push:
    branches:
      - main

env:
  Registry-Name: landair
  App-Name: livestream

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ env.Registry-Name }}.azurecr.io -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t ${{ env.Registry-Name }}.azurecr.io/${{ env.App-Name }}:latest .

      - name: Push the Docker image
        run: docker push ${{ env.Registry-Name }}.azurecr.io/${{ env.App-Name }}:latest
